import 'package:flutter/material.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:temaki_flutter/temaki_flutter.dart';

const Map<String, IconData> customIcons = {
  'bus': MdiIcons.bus,
  'tram': MdiIcons.tram,
  'train': MdiIcons.train,
  'platform': MdiIcons.busStopCovered,
  'pole': MdiIcons.busStop,
  'station': MdiIcons.home,
  'ticket_shop': TemakiIcons.ticket,
  'information': MdiIcons.informationVariant,
  'ticket_machine': TemakiIcons.vendingTickets,
  'parking': MdiIcons.parking,
  'taxi': MdiIcons.taxi,
  'toilet': MdiIcons.humanMaleFemale,
  'locker': TemakiIcons.vendingLockers,
  'trolley': MdiIcons.dolly,
  'phone_info': MdiIcons.phoneMessage,
  'phone': MdiIcons.phoneInTalk,
  'phone_emergency': MdiIcons.phoneAlert,
  'door': MdiIcons.door,
  'map': TemakiIcons.infoBoard,
  'path': TemakiIcons.pedestrian,
  'stairs': MdiIcons.stairs,
  'elevator': MdiIcons.elevatorPassenger,
  'escalator': MdiIcons.escalator,
  'cycle_barrier': TemakiIcons.cycleBarrier,
  'crosswalk': TemakiIcons.pedestrianCrosswalk,
  'traffic_signals': TemakiIcons.trafficSignals,
  'tram_crossing': TemakiIcons.crossingTramSolid,
  'rail_crossing': TemakiIcons.crossingRailSolid,
  'kerb': TemakiIcons.kerbRaised,
};
