const MAPBOX_API_TOKEN = 'YOUR TOKEN';
const MAPBOX_STYLE_URL = 'YOUR STYLE URL';

const DB_HOST = 'DATABASE HOST HERE';
const DB_PORT = 0;
const DB_USER = 'DATABASE USER NAME HERE';
const DB_PASSWORD = 'DATABASE PASSWORD HERE';
const DB_NAME = 'DATABASE NAME HERE';