include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true

  errors:
    avoid_slow_async_io: info

formatter:
  trailing_commas: preserve
  page_width: 100

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_positional_boolean_parameters: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_dynamic_calls: true
    avoid_escaping_inner_quotes: true
    avoid_null_checks_in_equality_operators: true
    avoid_setters_without_getters: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_interpolation_to_compose_strings: true
    prefer_null_aware_method_calls: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_const_declarations: true
    prefer_constructors_over_static_methods: true
    prefer_foreach: true
    prefer_void_to_null: true
    prefer_mixin: true
    prefer_const_constructors: true
    unnecessary_parenthesis: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_enums: true
    use_colored_box: true
    use_decorated_box: true
    use_is_even_rather_than_modulo: true
    use_raw_strings: true
    use_string_buffers: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    no_leading_underscores_for_local_identifiers: true
    no_adjacent_strings_in_list: true
    no_literal_bool_comparisons: true
    no_self_assignments: true
    noop_primitive_operations: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    document_ignores: true
    cast_nullable_to_non_nullable: true
    eol_at_end_of_file: true
    sized_box_shrink_expand: true
    omit_local_variable_types: true
    only_throw_errors: true
    parameter_assignments: true
    literal_only_boolean_expressions: true
    sort_unnamed_constructors_first: true
    throw_in_finally: true
    tighten_type_of_initializing_formals: true
    unawaited_futures: true
    dangling_library_doc_comments: false
